// src/modules/permissions/utils/permissionMockData.ts

import type {
  PermissionCatalogDto,
  PermissionDashboardDto,
  PermissionRoleDto,
  RolePermissionMatrixDto,
} from "../types/Permission.types";

export const PERMISSION_DASHBOARD_MOCK: PermissionDashboardDto = {
  summary: {
    totalPermissions: 186,
    activePermissions: 186,
    moduleCount: 12,
    sensitivePermissionCount: 18,
    roleAssignmentCount: 432,
    userOverrideCount: 27,
    lastSeededAtUtc: "2026-05-09T14:30:00Z",
  },
  modules: [
    {
      module: "users",
      displayNameKey: "permissions:modules.users",
      fallbackDisplayName: "Kullanıcı Yönetimi",
      totalPermissions: 22,
      sensitivePermissions: 3,
      tenantScoped: 20,
      selfScoped: 2,
      globalScoped: 0,
    },
    {
      module: "roles",
      displayNameKey: "permissions:modules.roles",
      fallbackDisplayName: "Rol Yönetimi",
      totalPermissions: 14,
      sensitivePermissions: 2,
      tenantScoped: 14,
      selfScoped: 0,
      globalScoped: 0,
    },
    {
      module: "permissions",
      displayNameKey: "permissions:modules.permissions",
      fallbackDisplayName: "Permission Yönetimi",
      totalPermissions: 18,
      sensitivePermissions: 5,
      tenantScoped: 18,
      selfScoped: 0,
      globalScoped: 0,
    },
    {
      module: "monitoring",
      displayNameKey: "permissions:modules.monitoring",
      fallbackDisplayName: "Audit ve Monitoring",
      totalPermissions: 16,
      sensitivePermissions: 6,
      tenantScoped: 16,
      selfScoped: 0,
      globalScoped: 0,
    },
    {
      module: "localization",
      displayNameKey: "permissions:modules.localization",
      fallbackDisplayName: "Lokalizasyon Yönetimi",
      totalPermissions: 10,
      sensitivePermissions: 1,
      tenantScoped: 0,
      selfScoped: 0,
      globalScoped: 10,
    },
  ],
  recentChanges: [
    {
      id: "chg-001",
      permissionCode: "permissions.role_permissions.sync.tenant",
      action: "synced",
      targetType: "role",
      targetName: "Admin",
      actorName: "Musa Bingöl",
      occurredAtUtc: "2026-05-09T15:10:00Z",
      correlationId: "corr-perm-001",
    },
    {
      id: "chg-002",
      permissionCode: "monitoring.audit.view.tenant",
      action: "granted",
      targetType: "role",
      targetName: "Property Manager",
      actorName: "Musa Bingöl",
      occurredAtUtc: "2026-05-09T14:48:00Z",
      correlationId: "corr-perm-002",
    },
    {
      id: "chg-003",
      permissionCode: "users.delete.tenant",
      action: "revoked",
      targetType: "user",
      targetName: "demo.admin@livemanage.local",
      actorName: "Musa Bingöl",
      occurredAtUtc: "2026-05-09T14:22:00Z",
      correlationId: "corr-perm-003",
    },
  ],
};

export const PERMISSION_CATALOG_MOCK: PermissionCatalogDto = {
  modules: PERMISSION_DASHBOARD_MOCK.modules,
  permissions: [
    {
      id: "perm-001",
      code: "permissions.view.tenant",
      module: "permissions",
      action: "view",
      scope: "tenant",
      group: "permissions",
      level: "1",
      descriptionKey: "permissions:catalog.descriptions.permissionsViewTenant",
      fallbackDescription: "Tenant içinde permission kataloğunu görüntüleme yetkisi.",
      isSensitive: false,
      riskLevel: "medium",
      isActive: true,
    },
    {
      id: "perm-002",
      code: "permissions.role_permissions.view.tenant",
      module: "permissions",
      action: "role_permissions.view",
      scope: "tenant",
      group: "permissions",
      level: "1",
      descriptionKey: "permissions:catalog.descriptions.rolePermissionsViewTenant",
      fallbackDescription: "Rollere atanmış permission kayıtlarını görüntüleme yetkisi.",
      isSensitive: false,
      riskLevel: "medium",
      isActive: true,
    },
    {
      id: "perm-003",
      code: "permissions.role_permissions.sync.tenant",
      module: "permissions",
      action: "role_permissions.sync",
      scope: "tenant",
      group: "permissions",
      level: "3",
      descriptionKey: "permissions:catalog.descriptions.rolePermissionsSyncTenant",
      fallbackDescription: "Rol permission matrisini toplu olarak senkronize etme yetkisi.",
      isSensitive: true,
      riskLevel: "high",
      isActive: true,
    },
    {
      id: "perm-004",
      code: "permissions.user_overrides.view.tenant",
      module: "permissions",
      action: "user_overrides.view",
      scope: "tenant",
      group: "permissions",
      level: "1",
      descriptionKey: "permissions:catalog.descriptions.userOverridesViewTenant",
      fallbackDescription: "Kullanıcı bazlı permission istisnalarını görüntüleme yetkisi.",
      isSensitive: true,
      riskLevel: "high",
      isActive: true,
    },
    {
      id: "perm-005",
      code: "permissions.effective.view.tenant",
      module: "permissions",
      action: "effective.view",
      scope: "tenant",
      group: "permissions",
      level: "2",
      descriptionKey: "permissions:catalog.descriptions.effectiveViewTenant",
      fallbackDescription: "Bir kullanıcının efektif permission sonucunu analiz etme yetkisi.",
      isSensitive: true,
      riskLevel: "critical",
      isActive: true,
    },
  ],
};

export const PERMISSION_ROLES_MOCK: PermissionRoleDto[] = [
  {
    id: "role-super-admin",
    name: "SuperAdmin",
    displayName: "Super Admin",
    description: "Sistem genelinde en geniş yönetim yetkilerine sahip rol.",
    isSystemRole: true,
    assignedPermissionCount: 5,
  },
  {
    id: "role-admin",
    name: "Admin",
    displayName: "Admin",
    description: "Tenant içi yönetim ve operasyon yetkilerine sahip rol.",
    isSystemRole: true,
    assignedPermissionCount: 4,
  },
  {
    id: "role-property-manager",
    name: "PropertyManager",
    displayName: "Property Manager",
    description: "Gayrimenkul ve operasyon süreçlerini yöneten rol.",
    isSystemRole: false,
    assignedPermissionCount: 2,
  },
];

export const ROLE_PERMISSION_MATRIX_MOCK: RolePermissionMatrixDto = {
  role: PERMISSION_ROLES_MOCK[1],
  permissions: PERMISSION_CATALOG_MOCK.permissions.map((permission, index) => ({
    permission,
    assigned: index <= 3,
    inherited: false,
    locked: permission.level === "4",
  })),
};